---
- name: Get easy_install-2.7 installer
  get_url: 
    url: "{{ installer_url }}"
    dest: "{{ installer_filepath }}"
  
- name: Install easy_install-2.7
  command: "python2.7 {{ installer_filepath }}"
  become: true
  become_pass: "{{ ansible_ssh_pass }}"

- name: Remove easy_install-2.7 installer
  command: "rm {{ installer_filepath }} -f"
...
